`default_nettype none
/*
  -----------------------------------------------------------------------------
   General Sound Top
  -----------------------------------------------------------------------------
*/
module gs_top (
    // clocks
    input wire            clk_bus,
    input wire            ce,
    input wire            reset,
    input wire            areset,

    // cpu input signals
    input wire [15:0]     a,
    input wire [7:0]      di,
    input wire            mreq_n,
    input wire            iorq_n,
    input wire            m1_n,
    input wire            rd_n,
    input wire            wr_n,

    // data out to cpu
    output wire           oe,
    output wire [7:0]     do_bus,

	// interface to sram
	inout  wire [7:0]    sram_d,
	output wire [20:0]   sram_a,
	output wire          sram_wr_n,
	output wire          sram_rd_n,

    // sound output
	output wire signed [14:0] out_l,
	output wire signed [14:0] out_r

);

// gs

wire [20:0] gs_mem_addr;
wire  [7:0] gs_mem_dout;
wire  [7:0] gs_mem_din;
wire        gs_mem_rd_n;
wire        gs_mem_wr_n;

gs gs 
(
    .RESET(reset),
    .CLK(clk_bus),
    .CE(ce), 
    
    .A(a),
    .DI(di),
    .DO(do_bus),
    .OE(oe),
    .WR_n(wr_n),
    .RD_n(rd_n),
    .IORQ_n(iorq_n),
    .M1_n(m1_n),

    .OUT_L(out_l),
    .OUT_R(out_r),

    .MA(gs_mem_addr),
    .MDI(gs_mem_din),
    .MDO(gs_mem_dout),
    .MRFSH_n(),
    .MWE_n(gs_mem_wr_n),
    .MRD_n(gs_mem_rd_n)
);

wire [7:0] rom_d;
// mem generated by: 
// hexdump -v -e '1/1 "%02x\n"' gs105b.rom > gs105b.mem
dprom #(.ADDRWIDTH(15), .MEM_INIT_FILE("gs105b.mem")) rom(
	.clock(clk_bus),
	.address_a(gs_mem_addr[14:0]),
	.q_a(rom_d)
);

wire is_rom = (gs_mem_addr < 32768);

assign gs_mem_din = (is_rom) ? rom_d : sram_d;
assign sram_d = (~gs_mem_wr_n) ? gs_mem_dout : 8'bz;
assign sram_a = gs_mem_addr;
assign sram_wr_n = gs_mem_wr_n;
assign sram_rd_n = gs_mem_rd_n;

endmodule
